name: pr_check_react18
on:
  workflow_dispatch:

jobs:
  jest-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: install
        run: yarn && yarn add react@18 react-dom@18 -D

